# autogenerated by /home/astivala/phd/ptgraph/buildversion.sh
# Fri Aug 10 09:43:43 EST 2012
def get_version():
    """
    Return version string containing global version number and 'build' date
    """
    return "Revision 4288:4291, Fri Aug 10 09:43:43 EST 2012"
